### ISSUE TITLE
problem with README.md

### ISSUE THREAD

**Issue by jooapa** [Klinoff-Corp/.github#2]
RELEASE OR REMOVE SECITON ABOUT klinoff-os

**Comment by miskamero** [comment]
Direct quote from README.md:
"Source code is still private as we are working on shaving the tiny imperfections"

Klinoff's reaction to inability to read:

![301072581-45ff5f6d-df7c-46b2-bc99-cfda5fe0be57](https://github.com/Klinoff-Corp/.github/assets/114387213/a05c9180-e314-48d5-bddc-ab23e9fa40ee)


Nöfnöf
